// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdN065_dqKb7GjXTupEPceSDse7oK8YDU',
    appId: '1:497767583121:web:fa693adc51cd5dbb1dde30',
    messagingSenderId: '497767583121',
    projectId: 'caissetectille',
    authDomain: 'caissetectille.firebaseapp.com',
    storageBucket: 'caissetectille.appspot.com',
    measurementId: 'G-ZQHPM999NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5N2PCLTcCG0oqslcMIz59T4iSOfPNdP0',
    appId: '1:497767583121:android:43c0892cfaeca9e71dde30',
    messagingSenderId: '497767583121',
    projectId: 'caissetectille',
    storageBucket: 'caissetectille.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT-XurQeXG44KnzFn4lQEZBblZ_tEZtO0',
    appId: '1:497767583121:ios:1e6ba7ed1f5a9f1b1dde30',
    messagingSenderId: '497767583121',
    projectId: 'caissetectille',
    storageBucket: 'caissetectille.appspot.com',
    iosBundleId: 'com.example.caisseTectille',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT-XurQeXG44KnzFn4lQEZBblZ_tEZtO0',
    appId: '1:497767583121:ios:1e6ba7ed1f5a9f1b1dde30',
    messagingSenderId: '497767583121',
    projectId: 'caissetectille',
    storageBucket: 'caissetectille.appspot.com',
    iosBundleId: 'com.example.caisseTectille',
  );
}
